2022-11-29 15:16:42,295 INFO    MainThread:5824 [wandb_setup.py:_flush():68] Configure stats pid to 5824
2022-11-29 15:16:42,295 INFO    MainThread:5824 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2022-11-29 15:16:42,295 INFO    MainThread:5824 [wandb_setup.py:_flush():68] Loading settings from c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\settings
2022-11-29 15:16:42,295 INFO    MainThread:5824 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-29 15:16:42,295 INFO    MainThread:5824 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-29 15:16:42,296 INFO    MainThread:5824 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221129_151642-3ac9u30j\logs\debug.log
2022-11-29 15:16:42,296 INFO    MainThread:5824 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221129_151642-3ac9u30j\logs\debug-internal.log
2022-11-29 15:16:42,296 INFO    MainThread:5824 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001535C0FE560>
2022-11-29 15:16:42,296 INFO    MainThread:5824 [wandb_init.py:init():516] calling init triggers
2022-11-29 15:16:42,296 INFO    MainThread:5824 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'epochs': 8000, 'batch_size': 10, 'dataset': ['tree0.dat', 'tree1.dat', 'tree10.dat', 'tree11.dat', 'tree12.dat', 'tree13.dat', 'tree14.dat', 'tree15.dat', 'tree16.dat', 'tree17.dat'], 'number of trees': 10, 'optim': Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 1e-05
    maximize: False
    weight_decay: 0
)}
2022-11-29 15:16:42,297 INFO    MainThread:5824 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 37vo8k4q
2022-11-29 15:16:42,298 INFO    MainThread:5824 [wandb_run.py:_finish():1746] finishing run paufeldman/autoencoder3/37vo8k4q
2022-11-29 15:16:42,298 INFO    MainThread:5824 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-11-29 15:16:42,299 INFO    MainThread:5824 [wandb_run.py:_restore():1932] restore
2022-11-29 15:16:42,299 INFO    MainThread:5824 [wandb_run.py:_restore():1938] restore done
2022-11-29 15:16:46,322 INFO    MainThread:5824 [wandb_init.py:init():569] starting backend
2022-11-29 15:16:46,322 INFO    MainThread:5824 [wandb_init.py:init():573] setting up manager
2022-11-29 15:16:46,333 INFO    MainThread:5824 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-29 15:16:46,337 INFO    MainThread:5824 [wandb_init.py:init():580] backend started and connected
2022-11-29 15:16:46,350 INFO    MainThread:5824 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-11-29 15:16:46,350 INFO    MainThread:5824 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-11-29 15:16:46,350 INFO    MainThread:5824 [wandb_init.py:init():658] updated telemetry
2022-11-29 15:16:46,385 INFO    MainThread:5824 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-29 15:16:49,479 WARNING MsgRouterThr:5824 [router.py:message_loop():77] message_loop has been closed
2022-11-29 15:16:49,479 WARNING MsgRouterThr:5824 [router.py:message_loop():77] message_loop has been closed
2022-11-29 15:16:51,431 ERROR   MainThread:5824 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "c:\Users\User\anaconda3\envs\py_torc\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "c:\Users\User\anaconda3\envs\py_torc\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "c:\Users\User\anaconda3\envs\py_torc\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
