2022-11-22 15:35:09,704 INFO    MainThread:15144 [wandb_setup.py:_flush():68] Configure stats pid to 15144
2022-11-22 15:35:09,704 INFO    MainThread:15144 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2022-11-22 15:35:09,704 INFO    MainThread:15144 [wandb_setup.py:_flush():68] Loading settings from c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\settings
2022-11-22 15:35:09,705 INFO    MainThread:15144 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-22 15:35:09,705 INFO    MainThread:15144 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-22 15:35:09,705 INFO    MainThread:15144 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221122_153509-3apylknu\logs\debug.log
2022-11-22 15:35:09,705 INFO    MainThread:15144 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221122_153509-3apylknu\logs\debug-internal.log
2022-11-22 15:35:09,706 INFO    MainThread:15144 [wandb_init.py:init():516] calling init triggers
2022-11-22 15:35:09,706 INFO    MainThread:15144 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 6000, 'batch_size': 1, 'dataset': ['ArteryObjAN1-17-55.dat'], 'number of trees': 1, 'optim': Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.0001
    maximize: False
    weight_decay: 0
)}
2022-11-22 15:35:09,706 INFO    MainThread:15144 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 3ophph5i
2022-11-22 15:35:09,708 INFO    MainThread:15144 [wandb_run.py:_finish():1746] finishing run paufeldman/autoencoder3/3ophph5i
2022-11-22 15:35:09,775 INFO    MainThread:15144 [jupyter.py:save_history():448] not saving jupyter history
2022-11-22 15:35:09,776 INFO    MainThread:15144 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-11-22 15:35:09,776 INFO    MainThread:15144 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-11-22 15:35:09,776 INFO    MainThread:15144 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-11-22 15:35:09,776 INFO    MainThread:15144 [wandb_run.py:_restore():1932] restore
2022-11-22 15:35:09,776 INFO    MainThread:15144 [wandb_run.py:_restore():1938] restore done
2022-11-22 15:35:11,788 INFO    MainThread:15144 [wandb_init.py:init():569] starting backend
2022-11-22 15:35:11,788 INFO    MainThread:15144 [wandb_init.py:init():573] setting up manager
2022-11-22 15:35:11,802 INFO    MainThread:15144 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-22 15:35:11,810 INFO    MainThread:15144 [wandb_init.py:init():580] backend started and connected
2022-11-22 15:35:11,848 INFO    MainThread:15144 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-11-22 15:35:11,848 INFO    MainThread:15144 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-11-22 15:35:11,848 INFO    MainThread:15144 [wandb_init.py:init():658] updated telemetry
2022-11-22 15:35:11,926 INFO    MainThread:15144 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-22 15:35:14,848 WARNING MsgRouterThr:15144 [router.py:message_loop():77] message_loop has been closed
2022-11-22 15:35:14,848 WARNING MsgRouterThr:15144 [router.py:message_loop():77] message_loop has been closed
2022-11-22 15:35:16,974 ERROR   MainThread:15144 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "c:\Users\User\anaconda3\envs\py_torc\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "c:\Users\User\anaconda3\envs\py_torc\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "c:\Users\User\anaconda3\envs\py_torc\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
